### ISSUE TITLE
Javascript errors in Production Build

### ISSUE THREAD

**Issue by jimjeffers** [siprasoftware/procal-website#3]
@ravi1889 @siprasoftware it looks like some of the third party libraries are throwing errors after the code is minified in the production build:

<img width="1199" alt="Screen Shot 2020-11-13 at 9 02 43 AM" src="https://user-images.githubusercontent.com/9150/99099340-24083200-258f-11eb-9c43-72ce9518ce82.png">

**Comment by siprasoftware** [comment]
This has been fixed and will commit changes along with SEO performance build.

**Comment by jimjeffers** [comment]
Thanks @siprasoftware
